image: maven:3.3.9-jdk-8

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - /root/.m2/repository/

stages:
- test
- build

myapplication_test:
stage: test
script:
- mvn clean test -B

myapplication_build:
stage: build
script:
- mvn package -B -Dmaven.test.skip
artifacts:
paths:
- target/myapplication-1.0.0.jar